/**
 * Firestore Report Service
 *
 * Provides CRUD operations for reports in Firestore.
 * Handles user reports and board reports for moderation.
 *
 * Data model:
 * - Reports are stored at /reports/{reportId}
 * - reportId is auto-generated by Firestore
 */

import type { ReportReason } from './socialTypes'
import { getFirebaseDb, USE_MOCK_AUTH } from './firebase'

// ============ Types ============

export type ReportTargetType = 'user' | 'board'

export interface ReportResult {
  success: boolean
  reportId?: string
  error?: string
}

// ============ Firestore Operations ============

/**
 * Create a new report
 */
export const createReport = async (
  reporterId: string,
  targetType: ReportTargetType,
  targetId: string,
  reason: ReportReason,
  details: string
): Promise<ReportResult> => {
  // Validation
  if (targetType === 'user' && reporterId === targetId) {
    return { success: false, error: "You can't report yourself" }
  }

  if (reason === 'other' && !details.trim()) {
    return { success: false, error: 'Please provide details for your report' }
  }

  if (USE_MOCK_AUTH) {
    // In mock mode, return success with a generated ID
    return {
      success: true,
      reportId: `mock-report-${Date.now()}`,
    }
  }

  try {
    const db = await getFirebaseDb()
    const { collection, addDoc, serverTimestamp } = await import('firebase/firestore')

    // Build the report document
    const reportData: Record<string, unknown> = {
      reporterId,
      reason,
      details: details.trim(),
      status: 'pending',
      createdAt: serverTimestamp(),
    }

    // Add target-specific fields
    if (targetType === 'user') {
      reportData.reportedUserId = targetId
    } else {
      reportData.reportedBoardId = targetId
    }

    const docRef = await addDoc(collection(db, 'reports'), reportData)

    return { success: true, reportId: docRef.id }
  } catch (error) {
    console.error('Error creating report:', error)
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to submit report',
    }
  }
}

/**
 * Check if user has already reported a specific target
 * Prevents duplicate reports
 */
export const hasUserReported = async (
  reporterId: string,
  targetType: ReportTargetType,
  targetId: string
): Promise<boolean> => {
  if (USE_MOCK_AUTH) {
    return false
  }

  try {
    const db = await getFirebaseDb()
    const { collection, query, where, getDocs } = await import('firebase/firestore')

    const targetField = targetType === 'user' ? 'reportedUserId' : 'reportedBoardId'

    const q = query(
      collection(db, 'reports'),
      where('reporterId', '==', reporterId),
      where(targetField, '==', targetId)
    )

    const snapshot = await getDocs(q)
    return !snapshot.empty
  } catch (error) {
    console.error('Error checking existing report:', error)
    return false
  }
}

/**
 * Get count of reports submitted by user since a timestamp
 * Used for rate limiting
 */
export const getReportCountSince = async (
  reporterId: string,
  sinceMs: number
): Promise<number> => {
  if (USE_MOCK_AUTH) {
    return 0
  }

  try {
    const db = await getFirebaseDb()
    const { collection, query, where, getDocs, Timestamp } = await import('firebase/firestore')

    const sinceTimestamp = Timestamp.fromMillis(sinceMs)

    const q = query(
      collection(db, 'reports'),
      where('reporterId', '==', reporterId),
      where('createdAt', '>=', sinceTimestamp)
    )

    const snapshot = await getDocs(q)
    return snapshot.size
  } catch (error) {
    console.error('Error counting reports:', error)
    return 0
  }
}
